// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.whocanfetchit.domain;

import com.whocanfetchit.domain.Bid;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Bid_Roo_Configurable {
    
    declare @type: Bid: @Configurable;
    
}
